"""add_aliases_to_persona

Revision ID: 6a5c6384936e
Revises: 94de52d3e589
Create Date: 2026-01-07 21:39:38.771783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a5c6384936e'
down_revision: Union[str, Sequence[str], None] = '94de52d3e589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('aliases')

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
