"""Refactor highlights to table

Revision ID: 94de52d3e589
Revises: d3eb12a07774
Create Date: 2026-01-06 22:22:42.658474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94de52d3e589'
down_revision: Union[str, Sequence[str], None] = 'd3eb12a07774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('highlights')
        batch_op.drop_column('memorable_quotes')
        batch_op.drop_column('low_points')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('highlights')
        batch_op.drop_column('memorable_quotes')
        batch_op.drop_column('low_points')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_points', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('memorable_quotes', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_points', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('memorable_quotes', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
