"""Add persona demographics

Revision ID: d3eb12a07774
Revises: e690b1bd6b9b
Create Date: 2026-01-06 22:01:37.131292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3eb12a07774'
down_revision: Union[str, Sequence[str], None] = 'e690b1bd6b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('persona', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('persona', sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('persona', sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('persona', sa.Column('alignment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.add_column('persona', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Alive'))
    op.add_column('persona', sa.Column('faction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'faction')
    op.drop_column('persona', 'status')
    op.drop_column('persona', 'level')
    op.drop_column('persona', 'alignment')
    op.drop_column('persona', 'class_name')
    op.drop_column('persona', 'race')
    op.drop_column('persona', 'gender')
    # ### end Alembic commands ###
